/**
 * 全局注册的 Element Plus 图标白名单
 *
 * 为什么集中在这里而不是在 main.js 里写 `Object.entries(ElementPlusIconsVue)`：
 * 全量注册（293 个）会让打包器无法摇树 —— 实测 dist 主 chunk 里 293 个图标名
 * 全部存在，而本项目实际只用到 69 个，约 76% 是纯浪费。
 * 图标在模板里既以标签形式使用（<el-icon><Search /></el-icon>），也以字符串形式
 * 使用（icon="ArrowLeft"、<component :is="section.icon" />），后者依赖全局注册，
 * 所以不能改成"按需 import 组件"，只能把注册表收窄成白名单。
 *
 * ⚠️ 新增图标必须同时加进这里。self-check 有一条断言会扫描全部源码，
 *    只要模板/JS 里引用了白名单之外的图标就会报红（避免"图标静静消失"）。
 *    白名单里出现没人用的图标同样会被提示。
 */
import {
  AlarmClock,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Bell,
  Bottom,
  Box,
  Calendar,
  Camera,
  ChatDotRound,
  ChatLineRound,
  Check,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled,
  Clock,
  Coin,
  Connection,
  Cpu,
  DataAnalysis,
  DataBoard,
  DataLine,
  Delete,
  Document,
  DocumentAdd,
  Download,
  EditPen,
  Files,
  Finished,
  FirstAidKit,
  Fold,
  FolderOpened,
  Guide,
  InfoFilled,
  Link,
  List,
  Lock,
  MagicStick,
  Microphone,
  Money,
  Monitor,
  Moon,
  Notebook,
  Odometer,
  PieChart,
  Plus,
  Printer,
  Promotion,
  Reading,
  Refresh,
  RefreshLeft,
  Right,
  Search,
  SetUp,
  Setting,
  Share,
  ShoppingCart,
  Stamp,
  Star,
  StarFilled,
  Tickets,
  Timer,
  Top,
  TrendCharts,
  Upload,
  User,
  VideoPause,
  VideoPlay,
  View,
  Warning,
  WarningFilled
} from '@element-plus/icons-vue'

/** 图标名 → 组件。main.js 遍历它做 app.component 注册。 */
export const APP_ICONS = {
  AlarmClock,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Bell,
  Bottom,
  Box,
  Calendar,
  Camera,
  ChatDotRound,
  ChatLineRound,
  Check,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled,
  Clock,
  Coin,
  Connection,
  Cpu,
  DataAnalysis,
  DataBoard,
  DataLine,
  Delete,
  Document,
  DocumentAdd,
  Download,
  EditPen,
  Files,
  Finished,
  FirstAidKit,
  Fold,
  FolderOpened,
  Guide,
  InfoFilled,
  Link,
  List,
  Lock,
  MagicStick,
  Microphone,
  Money,
  Monitor,
  Moon,
  Notebook,
  Odometer,
  PieChart,
  Plus,
  Printer,
  Promotion,
  Reading,
  Refresh,
  RefreshLeft,
  Right,
  Search,
  SetUp,
  Setting,
  Share,
  ShoppingCart,
  Stamp,
  Star,
  StarFilled,
  Tickets,
  Timer,
  Top,
  TrendCharts,
  Upload,
  User,
  VideoPause,
  VideoPlay,
  View,
  Warning,
  WarningFilled
}

/** 白名单里的图标名（self-check 用来自查一致性） */
export const APP_ICON_NAMES = Object.keys(APP_ICONS)
